# Generated by Django 4.2.6 on 2023-10-14 07:10

from django.db import migrations

# leave this migration empty will use it later#


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
    ]
